### ISSUE TITLE
internal server error when get defense shield info

### ISSUE THREAD

**Issue by ahsayde** [openvcloud/openvcloud#37]
### API
```/cloudapi/cloudspaces/getDefenseShield```

#### code
``/opt/code/github/openvcloud/openvcloud/actors/cloudapi/cloudapi__cloudspaces/methodclass/cloudapi_cloudspaces.py``

#### backtrace
``
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalRest.py", line 241, in execute_rest_call
    result = method(ctx=ctx, **ctx.params)
  File "/opt/code/github/openvcloud/openvcloud/cloudbroker/actorlib/authenticator.py", line 133, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/github/openvcloud/openvcloud/actors/cloudapi/cloudapi__cloudspaces/methodclass/cloudapi_cloudspaces.py", line 564, in getDefenseShield
    cloudspaceId = int(cloudspaceId)
ValueError: invalid literal for int() with base 10: '59d4f9edc8a63119e176f94e'
``

**Comment by grimpy** [comment]
API shoudl be removed (atleast for now) defensheield does not exists anymore
