### ISSUE TITLE
delete user from api returns internal server error

### ISSUE THREAD

**Issue by ahsayde** [openvcloud/openvcloud#39]
### Api
/cloudbroker/user/delete

### code
```
/usr/local/lib/python3.5/dist-packages/mongoengine/base/document.py
```

### backtrace
```
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalRest.py", line 241, in execute_rest_call
    result = method(ctx=ctx, **ctx.params)
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/auth.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/github/openvcloud/openvcloud/actors/cloudbroker/cloudbroker__user/methodclass/cloudbroker_user.py", line 85, in delete
    return self.deleteByGuid(user.id)
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/auth.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/github/openvcloud/openvcloud/actors/cloudbroker/cloudbroker__user/methodclass/cloudbroker_user.py", line 107, in deleteByGuid
    account.save()
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/data/models/Models.py", line 115, in save
    return Document.save(self)
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/document.py", line 303, in save
    self.validate(clean=clean)
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/data/models/Models.py", line 102, in validate
    return Document.validate(self, clean)
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/base/document.py", line 414, in validate
    raise ValidationError(message, errors=errors)
mongoengine.errors.ValidationError: ValidationError (Account:59d5f4cfc8a6311133d80972) (Value must be one of ['CONFIRMED', 'UNCONFIRMED', 'DISABLED']: ['status'] Only lists and tuples may be used in a list field: ['acl'])

```

**Comment by serboctor** [comment]
I can't reproduce it. @ahmedelsayed-93  said he will test it again.
