### ISSUE TITLE
internal server error when delete group with non-existing id

### ISSUE THREAD

**Issue by ahsayde** [openvcloud/openvcloud#40]
### API
/system/usermanager/deleteGroup

### code
```
/usr/local/lib/python3.5/dist-packages/mongoengine/base/fields.py
```
### backtrace
```
1
Traceback (most recent call last):
2
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/base/fields.py", line 450, in to_mongo
3
    return ObjectId(str(value))
4
  File "/usr/local/lib/python3.5/dist-packages/bson/objectid.py", line 110, in __init__
5
    self.__validate(oid)
6
  File "/usr/local/lib/python3.5/dist-packages/bson/objectid.py", line 206, in __validate
7
    _raise_invalid_id(oid)
8
  File "/usr/local/lib/python3.5/dist-packages/bson/objectid.py", line 52, in _raise_invalid_id
9
    " or a 24-character hex string" % oid)
10
bson.errors.InvalidId: 'fake_id' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
11
 
12
During handling of the above exception, another exception occurred:
13
 
14
Traceback (most recent call last):
15
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalRest.py", line 241, in execute_rest_call
16
    result = method(ctx=ctx, **ctx.params)
17
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/auth.py", line 83, in wrapper
18
    return func(*args, **kwargs)
19
  File "/opt/jumpscale9/app/portals/portalbase/system/system__usermanager/methodclass/system_usermanager.py", line 133, in deleteGroup
20
    group = j.portal.tools.models.system.Group.get(id)
21
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/data/models/Models.py", line 85, in get
22
    res = cls.objects.get(id=guid)
23
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 238, in get
24
    result = next(queryset)
25
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 1407, in __next__
26
    raw_doc = next(self._cursor)
27
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 1481, in _cursor
28
    self._cursor_obj = self._collection.find(self._query,
29
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 1515, in _query
30
    self._mongo_query = self._query_obj.to_query(self._document)
31
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/visitor.py", line 90, in to_query
32
    query = query.accept(QueryCompilerVisitor(document))
33
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/visitor.py", line 155, in accept
34
    return visitor.visit_query(self)
35
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/visitor.py", line 78, in visit_query
36
    return transform.query(self.document, **query.query)
37
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/transform.py", line 95, in query
38
    value = field.prepare_query_value(op, value)
39
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/base/fields.py", line 457, in prepare_query_value
40
    return self.to_mongo(value)
41
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/base/fields.py", line 453, in to_mongo
42
    self.error(str(e))
43
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/base/fields.py", line 155, in error
44
    raise ValidationError(message, errors=errors, field_name=field_name)
45
mongoengine.errors.ValidationError: 'fake_id' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
46
 
```

**Comment by ahsayde** [comment]
## moved to jumpscale/portal9 repo
