### ISSUE TITLE
internal server error when get machine info

### ISSUE THREAD

**Issue by ahsayde** [openvcloud/openvcloud#45]
### Scenario 
- create vm **vm1**
- stop **vm1** then start it
- get vm **vm1** info from api ``` /cloudapi/machines/get```
#### code
```/usr/local/lib/python3.5/dist-packages/requests/models.py```
#### backtrace
```
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalRest.py", line 241, in execute_rest_call
    result = method(ctx=ctx, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/cloudbroker/actorlib/authenticator.py", line 133, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/github/openvcloud/openvcloud/actors/cloudapi/cloudapi__machines/methodclass/cloudapi_machines.py", line 595, in get
    machine.modify(status=self.cb.machine.status(machine))
  File "/usr/local/lib/python3.5/dist-packages/cloudbroker/actorlib/cloudbroker.py", line 831, in status
    status = client.machine.status(machine.id, machine.stack.referenceId)
  File "/usr/local/lib/python3.5/dist-packages/cloudbroker/actorlib/gridmanager/machine.py", line 61, in status
    return self.client.nodes.GetVM(nodeid=nodeId, vmid='vm-{}'.format(machineId)).json()['status']
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/client/nodes_service.py", line 879, in GetVM
    return self.client.get(uri, None, headers, query_params, content_type)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/client/client.py", line 74, in get
    return self._handle_data(uri, data, headers, params, content_type, self.session.get)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/client/client.py", line 61, in _handle_data
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.195.61:8080/nodes/0cc47a740646/vms/vm-59dc70e3c8a6310322a372f5
```

**Comment by serboctor** [comment]
This is because of the issue I explained here https://github.com/openvcloud/openvcloud/issues/50. The VM was started on another stack from the OVC point of view, while in reality, it was still on its original stack. Accordingly, the GET API will return not found because OVC is querying a different stack from the one on which the VM is running.

**Comment by serboctor** [comment]
The Same issue might occur with the reboot action because it stops and starts the VM.
